#query legendary grass
SELECT DISTINCT ?pokemonName
WHERE {
?pokemon rdf:type pkmn:Pokemon ;
         pkmn:hasName ?pokemonName;
         pkmn:isLegendary 1.
FILTER(LANG(?pokemonName) = "en")
  {?pokemon pkmn:hasType1 "grass"}
  UNION
  {?pokemon pkmn:hasType2 "grass"}
}
