# All legendary Grass Types
SELECT DISTINCT ?pokemonName
WHERE {
  ?pokemon rdf:type pkmn:Pokemon ;
           pkmn:hasName ?pokemonName;
           pkmn:isLegendary 1.
  FILTER(LANG(?pokemonName) = "en")
  {?pokemon pkmn:hasType1 "grass"}
  UNION
  {?pokemon pkmn:hasType2 "grass"}
}


# All third-evolution of Fire Types starters
SELECT DISTINCT ?pokemonName
WHERE {
  ?pokemon rdf:type pkmn:Pokemon ;
           pkmn:hasName ?pokemonName;
           pkmn:hasAbility 'Blaze';
           pkmn:hasBaseTotal ?total.
  FILTER(LANG(?pokemonName) = "en"
         && ?total > 500)
  {?pokemon pkmn:hasType1 "fire"}
  UNION
  {?pokemon pkmn:hasType2 "fire"}
}


# All pokemon that resist a specific TYPE
SELECT ?pokemonName
WHERE {
  ?pokemon rdf:type pkmn:Pokemon ;
           pkmn:hasName ?pokemonName ;
           pkmn:againstTYPE ?multiplier .
  FILTER(LANG(?pokemonName) = "en" && ?multiplier < 1)
}